[env]
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder, colorize, send_on_enter, time
upload_protocol = esptool
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	olikraus/U8g2@^2.36.5
	https://github.com/dplasa/FTPClientServer.git
	https://github.com/jahrulnr/esp32-notification.git
	https://github.com/jahrulnr/esp32-microphone.git
	https://github.com/jahrulnr/esp32-speaker.git
	https://github.com/jahrulnr/esp32-mvc-framework.git
build_unflags =
	-Werror=all
	-Wimplicit-fallthrough
	-Wunused-but-set-variable
	-Wunused-function
	-fno-exceptions
build_flags =
	-DCORE_DEBUG_LEVEL=3
	-DLOG_LOCAL_LEVEL=5 ; ESP_LOG*
	-DCONFIG_ASYNC_TCP_PRIORITY=1
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-Wno-maybe-uninitialized
	-Wno-missing-field-initializers
	-Wno-error=sign-compare
	-Wno-error=double-promotion
	-Wno-type-limits
	-std=gnu++17
	-fexceptions

extra_scripts =
	tools/partition_manager.py
platform_packages =
	tool-esp32partitiontool@https://github.com/serifpersia/esp32partitiontool/releases/download/v1.4.5/esp32partitiontool-platformio.zip

[env:wemos-lolin32-lite]
platform = https://github.com/pioarduino/platform-espressif32/archive/refs/tags/55.03.30-2.tar.gz
board = wemos-lolin32-lite
framework = arduino
board_build.partitions = 4mb.csv
build_flags =
	${env.build_flags}
